version: "3"
services:
  rest-api:
    container_name: rest-api-iksans
    image: 9iksans/rest-api:1.0
    ports: 3000:3000
    environment: PORT=3000
    
  mongo:
    container_name: mongodb
    image: mongo:4.4.1
    ports: 
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=iksans
      - MONGO_INITDB_ROOT_PASSWORD=lulus3325
    volumes: 
      - /home/iksans/mongo-database:/data/db
